/* eslint-disable no-unused-vars */
import { default as DashboardLayout} from "./DashboardLayout"
import { default as Admin} from "./Admin"
import { default as AddJob} from "./AddJob"
import { default as AllJbobs} from "./AllJobs"
import { default as Landing} from "./Landing"
import { default as DeleteJob} from "./DeleteJob"
import { default as EditJob} from "./EditJob"
import { default as Error} from "./Error"
import { default as HomeLayout} from "./HomeLayout"
import { default as Login} from "./Login"
import { default as Profile} from "./Profile"
import { default as Register} from "./Register"
import { default as Stats} from "./Stats"